openapi: 3.0.0
info:
  title: marketplaces
  version: '1.0'
  description: Marketplace API for marketplaces project
  contact:
    name: Dalenys
    email: contact@dalenys.com
servers:
  - url: 'https://staging-payment.dlns.io'
    description: Staging
paths:
  /marketplaces/operators:
    get:
      summary: Your GET endpoint
      tags: []
      operationId: get-marketplaces
      description: This endpoint is for managing marketplaces.
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: ../models/marketplaces.v1.yaml
              examples: {}
    parameters: []
components:
  schemas: {}
