openapi: 3.0.0
info:
  title: submerchants.v1
  version: '1.0'
servers:
  - url: 'https://staging-payment.dlns.io/marketplaces'
    description: staging
paths:
  /submerchants:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-submerchants
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
    post:
      summary: ''
      operationId: post-submerchants
      responses:
        '201':
          description: Created
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  '':
                    type: string
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/submerchants.v1.yaml
components:
  schemas: {}
  securitySchemes:
    API Key - 1:
      name: API Key
      type: apiKey
      in: query
